name: Deploy Log Aggregator to Azure

on:
  push:
    branches:
      - master  # Change this to the branch you want to deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Make sure this matches the runtime stack chosen in Azure

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Zip application files
      run: zip -r logaggregator.zip .

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        slot-name: 'production'
        package: logaggregator.zip
        publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
