name: Deploy Log Aggregator to Azure

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r LogAggregatorTool/requirements.txt

    - name: Zip application files
      run: |
        zip -r logaggregator.zip LogAggregatorTool/
    
    - name: List directory contents for verification
      run: |
        echo "Listing contents of the root directory to confirm zip creation:"
        ls -lah

    - name: Login to Azure using Service Principal
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App using Azure CLI
      run: |
        az webapp deploy --name ${{ secrets.AZURE_WEBAPP_NAME }} \
                         --resource-group DynamicWebApplications \
                         --src-path logaggregator.zip
