name: Deploy Browser Policy Static Files

on:
  push:
    paths:
      - "browserPolicyDiffChecker/**"
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BROWSER_DIFF }}
          app_location: "browserPolicyDiffChecker/assets"
          deployment_action: "upload"
